### ISSUE TITLE
Having trouble downloading subtitles

### ISSUE THREAD

**Issue by iansquenet** [sameera-madushan/SubtitleBOX#18]
I have opened the .py file and video file, but it just shuts down and doesn't download the subtitles.

**Comment by sameera-madushan** [comment]
The error you're encountering might be because the SubDB API is currently down and inactive. Since the service is offline, it’s unable to fetch any subtitles, which causes issues even if you're using a VPN. Unfortunately, without the API being available, this tool won’t be able to retrieve subtitles for any videos.
