### ISSUE TITLE
All Video files fail to find Subtitles

### ISSUE THREAD

**Issue by Bugubugbug** [sameera-madushan/SubtitleBOX#20]
A few of the Subtitle websites are blocked in my country, so I'm aware that these sort of Githubs only work on a VPN, but,

I'm still encountering problems such as ;
"The selected file cannot be used to find subtitles"
https://i.imgur.com/68eJ0Rl.png

Does anybody have some input as to why it can't find Subtitles for every single Movie/Video I'm inputted?

**Comment by sameera-madushan** [comment]
The error you're encountering might be because the SubDB API is currently down and inactive. Since the service is offline, it’s unable to fetch any subtitles, which causes issues even if you're using a VPN. Unfortunately, without the API being available, this tool won’t be able to retrieve subtitles for any videos.
